---
title: "Hogwarts Admission Letters"
type: "exercise"
description: "Help Hogwarts write admission letters using React"
tags: "javascript, react, stateful components"
ignore:
- "node_modules/"
- "hogwarts-admission-letters.md"
